import type { SiteLanguage } from './site'

const copy = {
  zh: {
    nav: {
      links: [
        ['首页', '/'],
        ['AI 咨询', '/ai-consulting/'],
        ['Agent 落地', '/ai-agent-implementation/'],
        ['企业知识库', '/enterprise-knowledge-base/'],
        ['案例', '/case-studies/'],
        ['问答', '/faq/'],
        ['关于', '/about/'],
      ],
      diagnosis: '流程初诊',
      switchTitle: 'Switch to English',
      switchLabel: 'EN',
      openMenu: '打开导航菜单',
    },
    page: {
      breadcrumb: '面包屑',
      keyFacts: '页面要点',
      heroCta: '带一个真实流程来沟通',
      faqTitle: '服务常见问题',
      officialAnswers: 'PeterAI 官方回答',
      faqDescription: '答案说明 PeterAI 的通用方法和边界，具体项目以双方确认的诊断与验收口径为准。',
      evidenceEyebrow: '脱敏项目样本',
      evidenceTitle: '每个样本都回答四件事',
      evidenceDescription: '原来卡在哪里，做了什么，留下什么资产，哪些地方仍由人负责。',
      evidenceLabels: ['业务现场', '部署动作', '沉淀资产', '责任边界'],
      relatedEyebrow: '继续了解',
      relatedTitle: '把问题带到下一步',
      contactEyebrow: '微信联系',
      contactTitle: '扫描二维码，联系 Peter',
      contactDescription: '请先发送一句话说明你的行业，以及最想改善的一个流程。首次沟通只需提供完成判断所必需的信息。',
      location: '广东省中山市',
      privacy: '不要发送密钥、Cookie、完整客户名单或未经授权的敏感资料。',
      qrAlt: 'Peter 个人微信二维码',
      qrLabel: '微信扫码联系',
      profileAlt: 'PeterAI 创始人温泳扬（Peter）',
      profileName: '温泳扬（Peter）',
      profileRole: 'PeterAI 创始人 · 企业 AI 咨询与智能体落地顾问',
      profileDescription: 'PeterAI 的工作不是替企业购买更多工具，而是与老板和一线人员一起，把业务判断、流程标准与责任边界写进可运行、可验收的工作系统。',
    },
    footer: {
      company: '中山市彼得人工智能科技有限公司',
      descriptor: '广东中山 · 企业 AI 咨询与智能体落地',
      navLabel: '页脚导航',
      links: [
        ['企业 AI 咨询', '/ai-consulting/'],
        ['Agent 落地', '/ai-agent-implementation/'],
        ['企业知识库', '/enterprise-knowledge-base/'],
        ['脱敏项目样本', '/case-studies/'],
        ['常见问题', '/faq/'],
        ['联系 PeterAI', '/contact/'],
      ],
      principle: 'AI 替代动作，不替代责任。',
    },
    notFound: {
      title: '这个页面不存在',
      description: '你可以返回 PeterAI 首页，或查看企业 AI 咨询服务。',
      action: '返回首页',
    },
  },
  en: {
    nav: {
      links: [
        ['Home', '/'],
        ['AI Consulting', '/ai-consulting/'],
        ['Agent Implementation', '/ai-agent-implementation/'],
        ['Knowledge Base', '/enterprise-knowledge-base/'],
        ['Cases', '/case-studies/'],
        ['FAQ', '/faq/'],
        ['About', '/about/'],
      ],
      diagnosis: 'Workflow Diagnosis',
      switchTitle: 'Switch to Chinese',
      switchLabel: 'ZH',
      openMenu: 'Open navigation menu',
    },
    page: {
      breadcrumb: 'Breadcrumb',
      keyFacts: 'Page highlights',
      heroCta: 'Bring one real workflow to the conversation',
      faqTitle: 'Service FAQ',
      officialAnswers: 'PeterAI Official Answers',
      faqDescription: 'These answers describe PeterAI\'s general method and boundaries. Project-specific diagnosis and acceptance criteria are agreed by both parties.',
      evidenceEyebrow: 'Anonymized Project Samples',
      evidenceTitle: 'Every sample answers four questions',
      evidenceDescription: 'Where the workflow was stuck, what changed, which assets remained, and which responsibilities still belong to people.',
      evidenceLabels: ['Business context', 'Implementation', 'Assets retained', 'Responsibility boundary'],
      relatedEyebrow: 'Continue Exploring',
      relatedTitle: 'Take the question to the next step',
      contactEyebrow: 'WeChat Contact',
      contactTitle: 'Scan the QR code to contact Peter',
      contactDescription: 'Start with one sentence about your industry and the workflow you most want to improve. Share only the minimum information needed for an initial judgment.',
      location: 'Zhongshan, Guangdong, China',
      privacy: 'Do not send secrets, cookies, complete client lists, or unauthorized sensitive material.',
      qrAlt: 'Peter personal WeChat QR code',
      qrLabel: 'Scan with WeChat',
      profileAlt: 'Peter, founder of PeterAI',
      profileName: 'Peter Wen',
      profileRole: 'Founder of PeterAI · Enterprise AI and Agent Implementation Consultant',
      profileDescription: 'PeterAI does not help companies buy more tools. We work with owners and frontline teams to encode business judgment, process standards, and accountability into systems that can run and be accepted.',
    },
    footer: {
      company: 'Zhongshan Peter Artificial Intelligence Technology Co., Ltd.',
      descriptor: 'Zhongshan, Guangdong · Enterprise AI Consulting and Agent Implementation',
      navLabel: 'Footer navigation',
      links: [
        ['Enterprise AI Consulting', '/ai-consulting/'],
        ['Agent Implementation', '/ai-agent-implementation/'],
        ['Enterprise Knowledge Base', '/enterprise-knowledge-base/'],
        ['Anonymized Project Samples', '/case-studies/'],
        ['FAQ', '/faq/'],
        ['Contact PeterAI', '/contact/'],
      ],
      principle: 'AI replaces actions, not accountability.',
    },
    notFound: {
      title: 'This page does not exist',
      description: 'Return to the PeterAI homepage or explore enterprise AI consulting.',
      action: 'Back to home',
    },
  },
} as const

export const getUiCopy = (language: SiteLanguage) => copy[language]
